name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build
      
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: production-files
          path: ./distt

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: production-files
          path: ./dist
